### ISSUE TITLE
Fusion center NTP local

### ISSUE THREAD

**Issue by RandomStudentA** [rwth-ti/gr-localization#3]
When I run the fusion center the NTP ip shows that its local , is there a configuration I missed somewhere since to my understanding for another pc to reach I would need a non-local IP for the  ./receiver.py --fusion-center "fusion_center_ip_addr". 
![capture](https://user-images.githubusercontent.com/37094035/38714858-c5265b4e-3f0a-11e8-9983-b4d346fa7dd9.PNG)
![capture](https://user-images.githubusercontent.com/37094035/38714872-d95d2494-3f0a-11e8-949c-ec8dd6ddfd95.PNG)

**Comment by johschmitz** [comment]
Did you read the README? Also you can use --help for each python script.

**Comment by RandomStudentA** [comment]
I tried to use use -help only thing I saw close to what I need is -s but it didn't seem to work ./fusion_center.py -s 192.168.111.132

**Comment by johschmitz** [comment]
I don't exactly understand what you are trying but what you have to do is to run the fusion center on one of the computers then write down it's ip or hostname and provide that to the receiver application on the other computer with the --fusion_center option. You can use ifconfig to find out the ip address.

**Comment by RandomStudentA** [comment]
I'm using Vmware to run the program , for the computer itself its ip and subnet is this 
![capture](https://user-images.githubusercontent.com/37094035/38848900-2cfd6d14-423c-11e8-928c-2399cb4c4d41.PNG)
while for the Vmware that share the localhost Ip it shows this 
![capture](https://user-images.githubusercontent.com/37094035/38848946-51056de2-423c-11e8-8afd-759ada066f50.PNG)
so for the second computer for the  ./receiver.py --fusion-center "fusion_center_ip_addr" which Ipaddress should I type?

**Comment by johschmitz** [comment]
I am sorry, but I am afraid I can't help much with th VMware configuration. I am sure it can't be that hard though. Why don't you first try the emulation mode where everything runs on the same computer? Try executing the script run_all_tdoa_emu.sh in the apps folder.

**Comment by RandomStudentA** [comment]
Thanks for suggestion , I ran them in the same Vmware and I think it works now.
Starting with VM1
![1b](https://user-images.githubusercontent.com/37094035/38853368-a036b6d8-424f-11e8-8713-3aa0842c5005.PNG)
Typing code in VM2
![a2](https://user-images.githubusercontent.com/37094035/38853386-aa1ec12c-424f-11e8-999b-8bd35fe4640a.PNG)
Finally what shows up in VM1
![1a](https://user-images.githubusercontent.com/37094035/38853397-afa72b3e-424f-11e8-9be4-508f5a84ac05.PNG)
To my understanding this is what its suppose to happen right? After this all I have to do is have a transmitter transmit and it should show up right?
