### ISSUE TITLE
Both device on the same location.

### ISSUE THREAD

**Issue by RandomStudentA** [rwth-ti/gr-localization#4]
I have two machines with antenna and gps on it , after setting up both westbridge it appears on the top right of the gui but the location of both them seem to be the exact same place with one above the other but physically they're not that close. What am I doing wrong?

**Comment by johschmitz** [comment]
You have to specify their location. For example you can do it by clicking
in the map. There should be a button for that in the list of receivers. You
can also obtain this information from their GPSDO.

RandomStudentA <notifications@github.com> schrieb am Mi., 9. Mai 2018,
05:17:

**Comment by RandomStudentA** [comment]
I see , but after that what do I do? How will the actual TDOA happen? How does the transmitter appear/what do I use for the transmitter?

**Comment by johschmitz** [comment]
Okay if you really need step by step instructions you can send me an email
and we can see what we can do.

Also did you read the paper?
http://ti.rwth-aachen.de/publications/abstract.php?q=db&table=proceeding&id=1064

Basically it works for different types of signals. It just takes
synchronized snapshots of a number of samples at each receiver and
correlates them in the fusion center to obtain the TDOAs. It then
determines the location of the source based on those TDOAs and the sensor
locations. The update rate depends mostly on the CPU of your fusion center
and the backhaul network connection. However the fusion center code is
written in Python and not highly optimized, so some speed-up is definitely
possible. I don't recommend running with more than 10Hz update rate.

RandomStudentA <notifications@github.com> schrieb am Mi., 9. Mai 2018,
11:13:

**Comment by RandomStudentA** [comment]
I really need step by step instruction , I'm totally lost.

**Comment by RandomStudentA** [comment]
Opps , can I have your email please , thank you.

**Comment by johschmitz** [comment]
You can find my contact information here: http://ti.rwth-aachen.de/staff/page.php?user=Johannes%20Schmitz

**Comment by RandomStudentA** [comment]
ok thank you
